# Generated by Django 4.2.11 on 2025-07-21 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_job_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='image',
            field=models.ImageField(default=0, upload_to='jobs/'),
            preserve_default=False,
        ),
    ]
